import test from "node:test";
import assert from "node:assert/strict";
import { planBeacons as generate, BEACON_PROFILES, snapBeaconToGraph } from "./beaconPlacement.js";
const box=(x,y,width,height)=>[{x,y},{x:x+width,y},{x:x+width,y:y+height},{x,y:y+height}];
// Historical seed-spacing tests explicitly exercise the centerline baseline, not the new default.
function planBeacons(input){const nodes=input.graph.nodes;const maxX=nodes.reduce((m,n)=>Math.max(m,n.worldX),0),maxY=nodes.reduce((m,n)=>Math.max(m,n.worldY),0);return generate({...input,configuration:{...input.configuration,placementStrategy:'centerline'},floorGeometry:{floors:[...new Set(nodes.map(n=>n.floorId))].map(floorId=>({floorId,boundaries:[box(-20,-20,maxX+40,maxY+40)],walkableAreas:[box(-20,-20,maxX+40,maxY+40)]}))}});}
const n=(id,x,y=0,type="Corridor")=>({id,floorId:"G",x:x*10,y:y*10,worldX:x,worldY:y,type,metadata:{}});
const line={nodes:[n("a",0,0,"Entrance"),n("b",22,0,"Exit")],edges:[{id:"ab",source:"a",target:"b",distance:22}]};
test("places and optimizes 5.5 m spacing with endpoint anchors",()=>{const r=planBeacons({graph:line});assert.equal(r.beacons.length,5);assert.equal(r.statistics.anchorBeacons,2);assert.equal(r.statistics.averageSpacing,5.5);assert.equal(r.coverage.estimatedPercent,100);assert.equal(r.warnings.length,0);});
test("intermediate graph nodes do not inflate placement",()=>{const graph={nodes:Array.from({length:9},(_,i)=>n(String(i),i*2.75)),edges:Array.from({length:8},(_,i)=>({id:String(i),source:String(i),target:String(i+1),distance:2.75}))};const r=planBeacons({graph});assert.equal(r.beacons.length,5);assert.equal(r.statistics.averageSpacing,5.5);});
test("junction is anchored once across branches",()=>{const graph={nodes:[n("j",0),n("a",11),n("b",0,11),n("c",-11)],edges:["a","b","c"].map(id=>({id,source:"j",target:id,distance:11}))};const r=planBeacons({graph});assert.equal(r.beacons.filter(b=>b.nodeId==="j").length,1);assert.equal(r.beacons.find(b=>b.nodeId==="j").type,"Anchor");});
test("manual edits detect missing anchors, duplicates and uncovered edges",()=>{const r=planBeacons({graph:line,configuration:{mode:"manual",beacons:[]}});assert.ok(r.warnings.some(w=>w.code==="missing-anchor"));assert.ok(r.warnings.some(w=>w.code==="uncovered-edge"));const original=planBeacons({graph:line});const edited=planBeacons({graph:line,configuration:{mode:"hybrid",beacons:[...original.beacons,{...original.beacons[0],id:"dup"}]}});assert.ok(edited.warnings.some(w=>w.code==="duplicate-beacons"));});
test("snaps manual beacon to a graph edge",()=>{const b=snapBeaconToGraph({floorId:"G",worldX:5,worldY:1},line,2);assert.equal(b.worldY,0);assert.equal(b.edgeId,"ab");});
test("disabled beacons are excluded and configured spacing survives recalculation",()=>{const original=planBeacons({graph:line,configuration:{spacing:6}});const beacons=original.beacons.map(b=>b.nodeId==="a"?{...b,enabled:false}:b);const r=planBeacons({graph:line,configuration:{...original.configuration,beacons}});assert.equal(r.configuration.spacing,6);assert.equal(r.statistics.disabledBeacons,1);assert.ok(r.warnings.some(w=>w.code==="missing-anchor"));});
test("floor transition endpoints become anchors without placing inside the connector",()=>{const graph={nodes:[n("a",0),{...n("b",0),floorId:"L1"}],edges:[{id:"lift",source:"a",target:"b",distance:4}]};const r=planBeacons({graph});assert.equal(r.beacons.length,2);assert.equal(r.statistics.anchorBeacons,2);assert.equal(r.coverage.totalLength,0);});
test("warns on unavoidable short spacing",()=>{const r=planBeacons({graph:{nodes:[n("a",0,0,"Entrance"),n("b",3,0,"Exit")],edges:[{...line.edges[0],distance:3}]}});assert.ok(r.warnings.some(w=>w.code==="spacing-too-small"));});
test("missing geometry fails closed instead of generating unsafe beacons",()=>{const r=generate({graph:line});assert.equal(r.beacons.length,0);assert.ok(r.warnings.some(w=>w.code==="geometry-rejected"));assert.equal(r.quality.overallScore,0);});
test("geometry-conflicting beacon moves to nearest valid edge point",()=>{const region=box(-1,-1,24,2),r=generate({graph:line,floorGeometry:{floors:[{floorId:"G",boundaries:[region],walkableAreas:[region],restrictedAreas:[box(5,-1,1,2)]}]}});assert.equal(r.geometryValidation.relocated,1);assert.ok(r.beacons.every(b=>b.worldX<5||b.worldX>6));assert.ok(r.beacons.every(b=>b.installationType==="Ceiling"&&b.mountingHeight===3&&b.installationStatus==="Planned"));});
test("optimization chooses a feasible spacing rather than blindly rounding",()=>{const r=planBeacons({graph:{nodes:[n("a",0,0,"Entrance"),n("b",31,0,"Exit")],edges:[{id:"ab",source:"a",target:"b",distance:31}]},configuration:{spacing:6}});assert.ok(r.statistics.minimumSpacing>=5);assert.ok(r.statistics.maximumSpacing<=6);assert.equal(r.warnings.length,0);});
test("recalculation repairs stale edge references and applies a changed radius",()=>{const original=planBeacons({graph:line});const moved={...original.beacons[2],worldX:11,x:110,edgeOffset:0};const r=planBeacons({graph:line,profile:{...BEACON_PROFILES[0],coverageRadius:8},configuration:{beacons:[moved]}});assert.equal(r.beacons[0].edgeOffset,11);assert.equal(r.beacons[0].coverageRadius,8);});
test("a graph crossing a wall is warned, never scored as fully covered",()=>{const region=box(-1,-1,24,2),r=generate({graph:line,floorGeometry:{floors:[{floorId:"G",boundaries:[region],walkableAreas:[region],walls:[{points:[{x:11,y:-1},{x:11,y:1}],width:.2}]}]}});assert.ok(r.coverage.estimatedPercent<100);assert.ok(r.warnings.some(w=>w.code==="graph-geometry-conflict"));});
test("duplicate node-attached beacons reduce quality and duplicate graph IDs are rejected",()=>{const original=planBeacons({graph:line});const r=planBeacons({graph:line,configuration:{beacons:[...original.beacons,{...original.beacons[0],id:"duplicate"}]}});assert.ok(r.quality.spacingScore<100);assert.ok(r.quality.overallScore<100);assert.throws(()=>planBeacons({graph:{...line,edges:[...line.edges,...line.edges]}}));});
test("same-floor edge distances cannot fabricate physical beacon spacing",()=>{assert.throws(()=>planBeacons({graph:{...line,edges:[{...line.edges[0],distance:11}]}}),/does not match/);});
test("traverses large graph without recursion",()=>{const count=10001;const graph={nodes:Array.from({length:count},(_,i)=>n(String(i),i)),edges:Array.from({length:count-1},(_,i)=>({id:String(i),source:String(i),target:String(i+1),distance:1}))};const begin=performance.now();const r=planBeacons({graph,profile:BEACON_PROFILES[0]});assert.ok(r.beacons.length>1000);assert.equal(r.statistics.anchorBeacons,0);console.log(`beacon benchmark: ${count} nodes, ${r.beacons.length} beacons, ${(performance.now()-begin).toFixed(1)} ms`);});
