import React,{useEffect,useState} from "react";
import {BEACON_PROFILES,planBeacons} from "../engines/beaconPlacement.js";
import {DEFAULT_PLANNING_SETTINGS,BEACON_ANCHOR_TYPES} from "../engines/deploymentPlanner.js";
import {saveDeployment,loadDeployment,duplicateDeployment,deleteDeployment} from "../models/deployments.js";
import {deploymentDocument,beaconCsv,coverageSummary,downloadFile,exportCanvasPng,compareDeployments} from "../models/deploymentExport.js";

const format=v=>v==null?"Not analyzed":typeof v==="number"?v.toFixed(2):String(v);
const labels={totalBeacons:"Total beacons",activeBeacons:"Enabled beacons",navigationBeacons:"Navigation",disabledBeacons:"Disabled",coveragePercent:"Coverage %",deadZonePercent:"Dead zone %",overlapPercent:"Overlap %",averageSpacing:"Average route-station spacing (m)",minimumSpacing:"Minimum route-station spacing (m)",maximumSpacing:"Maximum route-station spacing (m)",maximumGap:"Maximum coverage gap (m)",minimumGap:"Minimum coverage gap (m)",deploymentQuality:"Deployment quality",installationCost:"Estimated installation cost",warnings:"Warnings"};
function DraftField({label,value,onCommit,type="number",...props}) {
  const [draft,setDraft]=useState(String(value??""));
  useEffect(()=>setDraft(String(value??"")),[value]);
  return <label>{label}<input {...props} type={type} value={draft} required={type==="number"} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")e.target.blur();}} onBlur={e=>{if(!e.target.checkValidity()){e.target.reportValidity();setDraft(String(value??""));return;}const next=type==="number"?Number(draft):draft;if(next!==value)onCommit(next);}}/></label>;
}
export default function BeaconPanel({project,update,setTool,selection,setSelection,planner,error,focus}) {
  const [localError,setLocalError]=useState(""),[name,setName]=useState("Version A"),[versionId,setVersionId]=useState(project.activeDeploymentId||""),[compareId,setCompareId]=useState("");
  const [custom,setCustom]=useState({...BEACON_PROFILES[0],modelName:"My beacon profile"});
  const result=project.beaconPlan,settings={...DEFAULT_PLANNING_SETTINGS,defaultProfileId:project.beaconProfile?.id||DEFAULT_PLANNING_SETTINGS.defaultProfileId,...project.planningSettings},profiles=[...BEACON_PROFILES,...(project.beaconProfiles||[])];
  const selected=result?.beacons.find(b=>b.id===selection),inspector=planner.inspector?.id===selection?planner.inspector:null,versions=project.deployments||[],a=versions.find(v=>v.id===versionId),b=versions.find(v=>v.id===compareId),comparison=a&&b?compareDeployments(a,b):null;
  useEffect(()=>{setVersionId(project.activeDeploymentId||"");const v=versions.find(v=>v.id===project.activeDeploymentId);if(v)setName(v.name);},[project.activeDeploymentId]);
  const command=(action,data)=>{setLocalError("");planner.command(action,data,{selection});};
  const edit=patch=>command("patch",{id:selection,patch});
  const setting=(field,value)=>result?command("configure",{[field]:value}):update({...project,planningSettings:{...settings,[field]:value}});
  function save(action){try{update(action());setLocalError("");}catch(e){setLocalError(e.message);}}
  function saveProfile(){try{planBeacons({graph:{nodes:[],edges:[]},profile:custom});if(!custom.modelName.trim())throw new Error("Profile name is required.");update({...project,beaconProfiles:[...(project.beaconProfiles||[]),{...custom,id:`custom-${crypto.randomUUID()}`}]});setLocalError("");}catch(e){setLocalError(e.message);}}
  async function exportFile(kind){try{const doc=deploymentDocument(project);if(kind==="json")downloadFile("deployment.json",doc);if(kind==="csv")downloadFile("beacons.csv",beaconCsv(result.beacons),"text/csv;charset=utf-8");if(kind==="coverage"){if(!project.coverageAnalysis)throw new Error("Analyze coverage first.");downloadFile("coverage-report.json",coverageSummary(project.coverageAnalysis));}if(kind==="quality")downloadFile("quality-report.json",{quality:result.quality,statistics:result.statistics,warnings:result.warnings,settings,isRFSimulation:false});if(kind==="png")await exportCanvasPng(document.querySelector('svg[aria-label="Infinite floor planning canvas"]'));setLocalError("");}catch(e){setLocalError(e.message);}}
  return <section className="panel-section graph-panel deployment-panel"><h2>Deployment planner</h2><small>{planner.busy?"Updating live analysis…":"Live geometry + graph analysis"} · no RF simulation</small>{result&&<p role="status"><strong>{result.beacons.length} IW beacons generated</strong>{project.floorAnalysis?.method==="aligned-venue-reference"&&<small>Blue: navigation beacons · red: API access points. Review this initial draft before installation.</small>}</p>}
    <div className="button-row"><button disabled={planner.busy} onClick={()=>command("generate",{})}>Generate placement</button><button disabled={!result} onClick={()=>setTool("beaconInsert")}>Insert beacon</button></div><small>Topology-aware mounting: graph references guide spacing, not final coordinates.</small>
    <label className="check-label"><input type="checkbox" checked={project.beaconLabelsVisible!==false} onChange={e=>update({...project,beaconLabelsVisible:e.target.checked})}/>Show beacon IDs</label><DraftField type="text" label="Beacon ID prefix" value={settings.beaconPrefix} maxLength={20} onCommit={value=>setting("beaconPrefix",value.trim())}/><small>Prefix applies to new beacons only. Existing IDs are preserved.</small><label>Select beacon<select value={selection||""} onChange={e=>{setSelection(e.target.value||null);setTool("select");}}><option value="">Choose beacon</option>{result?.beacons.map(b=><option key={b.id} value={b.id}>{b.id}{b.locked?" · locked":""}</option>)}</select></label>
    {selected&&<section className="beacon-inspector"><h3>Beacon inspector</h3><label>ID<input value={selected.id} readOnly/></label><small>Floor: {selected.floorId}<br/>Placement strategy: {selected.placementStrategy||'Manual / legacy'}<br/>Reference corridor: {inspector?.topology?.classification||'Unknown'} · width {format(inspector?.topology?.corridorWidth)} m<br/>Graph reference offset: {format(selected.referenceDistance)} m</small>
      <p>Type: Navigation beacon</p>
      <label>Beacon profile<select value={selected.profileId} onChange={e=>{const p=profiles.find(p=>p.id===e.target.value);edit({profileId:p.id,coverageRadius:p.coverageRadius,reliableRadius:p.reliableRadius??p.coverageRadius,marginalRadius:p.marginalRadius??p.coverageRadius*4/3,installationType:p.installationType||(p.mountType==="Outdoor"?"Pole":p.mountType),mountingHeight:p.recommendedHeight});}}>{profiles.map(p=><option key={p.id} value={p.id}>{p.modelName}</option>)}</select></label>
      <label>Mount type<select value={selected.installationType} onChange={e=>edit({installationType:e.target.value})}>{["Ceiling","Wall","Pole"].map(t=><option key={t}>{t}</option>)}</select></label>
      <DraftField label="Mounting height (m)" min=".1" step="any" value={selected.mountingHeight} onCommit={value=>edit({mountingHeight:value})}/>
      <div className="field-grid">{["worldX","worldY"].map(field=><DraftField key={`${selected.id}-${field}`} label={field==="worldX"?"X (m)":"Y (m)"} disabled={selected.locked} step="any" value={selected[field]} onCommit={value=>{const scale=Number(project.widthMeters)/Number(project.drawingWidthPixels);command("move",{id:selected.id,floorId:selected.floorId,x:field==="worldX"?value/scale:selected.x,y:field==="worldY"?value/scale:selected.y,worldX:field==="worldX"?value:selected.worldX,worldY:field==="worldY"?value:selected.worldY});}}/>)}</div>
      {[["coverageRadius","Coverage radius"],["reliableRadius","Reliable radius"],["marginalRadius","Marginal radius"]].map(([field,label])=><DraftField key={`${selected.id}-${field}`} label={`${label} (m)`} min=".1" step="any" value={selected[field]??settings[field]} onCommit={value=>edit({[field]:value})}/>)}
      <small>Nearest graph edge: {inspector?.nearestEdge?`${inspector.nearestEdge.id} (${inspector.nearestEdge.distance.toFixed(2)} m)`:"None"}<br/>Nearest POI: {inspector?.nearestPoi?`${inspector.nearestPoi.name||inspector.nearestPoi.id} (${inspector.nearestPoi.distance.toFixed(2)} m)`:"None"}<br/>Unique coverage contribution: {format(inspector?.coverageContribution)} m²<br/>Coverage footprint: {format(inspector?.coverageFootprint)} m²</small><small>Contribution is sampled area lost if only this beacon is removed; overlap is not counted twice.</small>
      <label>Orientation (degrees)<input type="number" defaultValue={selected.orientation??""} key={`${selected.id}-${selected.orientation}`} onBlur={e=>edit({orientation:e.target.value===""?null:Number(e.target.value)})}/></label><DraftField type="text" label="Notes" value={selected.notes||""} onCommit={value=>edit({notes:value})}/>
      <label>Installation status<select value={selected.installationStatus} onChange={e=>edit({installationStatus:e.target.value})}>{["Planned","Installed","Verified","Needs review"].map(t=><option key={t}>{t}</option>)}</select></label>
      <div className="button-row"><button onClick={()=>edit({enabled:selected.enabled===false})}>{selected.enabled===false?"Enable beacon":"Disable beacon"}</button><button onClick={()=>edit({locked:!selected.locked})}>{selected.locked?"Unlock beacon":"Lock beacon"}</button><button onClick={()=>command("duplicate",{id:selection})}>Duplicate beacon</button><button className="danger" disabled={selected.locked} onClick={()=>command("delete",{id:selection})}>Delete beacon</button></div><small>{selected.locked?"Position and deletion locked; recalculation preserves this beacon.":"Drag or edit coordinates; valid off-center positions are preserved."}</small>{inspector?.warnings.map((w,i)=><p className="warning-text" key={i}>{w.message}</p>)}
    </section>}
    <details open><summary>Smart recalculation</summary><div className="button-row"><button disabled={!selected||planner.busy} onClick={()=>command("recalculate",{scope:"selected",id:selection})}>Recalculate selected</button><button disabled={!selected||planner.busy} onClick={()=>command("recalculate",{scope:"floor",id:selection})}>Recalculate floor</button></div><button disabled={!result||planner.busy} onClick={()=>command("recalculate",{scope:"project"})}>Recalculate entire project</button><small>Revalidates existing positions, never regenerates IDs. Locked beacons stay fixed.</small></details>
    <details><summary>Project planning settings</summary><label>Default beacon profile<select value={settings.defaultProfileId} onChange={e=>setting("defaultProfileId",e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{p.modelName}</option>)}</select></label>
      {[["spacing","Default spacing (m)",5,6],["reliableRadius","Default reliable radius (m)",.1],["marginalRadius","Default marginal radius (m)",.1],["coverageTarget","Coverage target (%)",0,100],["wallClearance","Wall clearance (m)",0],["installationCost","Installation cost per enabled beacon",0]].map(([field,label,min,max])=><DraftField key={field} label={label} min={min} max={max} step="any" value={settings[field]} onCommit={value=>setting(field,value)}/>)}
      <DraftField type="text" label="Cost currency" value={settings.currency} onCommit={value=>setting("currency",value)}/><label>Planning mode<select value={settings.planningMode} onChange={e=>setting("planningMode",e.target.value)}>{["automatic","manual","hybrid"].map(m=><option key={m}>{m}</option>)}</select></label><label>Coverage threshold<select value={settings.coverageThreshold} onChange={e=>setting("coverageThreshold",e.target.value)}><option value="reliable">Reliable radius</option><option value="marginal">Marginal radius</option><option value="nominal">Nominal coverage radius</option></select></label>
      <small>Radius classes are geometric assumptions, not RSSI. Settings reanalyze immediately; only Generate changes the layout.</small>
      {[["narrowWidth","Narrow corridor limit (m)"],["mediumWidth","Medium corridor limit (m)"],["openAreaWidth","Open area threshold (m)"],["mountingInset","Mounting inset (m)"],["topologySearchRadius","Nearby entrance / POI radius (m)"]].map(([field,label])=><DraftField key={field} label={label} min=".01" step="any" value={settings[field]} onCommit={value=>setting(field,value)}/>)}
      <DraftField label="Additional area-beacon budget" min="0" max="200" step="1" value={settings.additionalBeaconBudget} onCommit={value=>setting('additionalBeaconBudget',value)}/><small>Stops adding when the sampled target is reached. Route spacing refers to graph stations, not physical mounting distances.</small>
      {BEACON_ANCHOR_TYPES.map(type=><label key={type} className="check-label"><input type="checkbox" checked={settings.anchorTypes.includes(type)} onChange={e=>setting("anchorTypes",e.target.checked?[...settings.anchorTypes,type]:settings.anchorTypes.filter(t=>t!==type))}/>Cover {type}</label>)}<label className="check-label"><input type="checkbox" checked={settings.junctionAnchors} onChange={e=>setting("junctionAnchors",e.target.checked)}/>Cover large junctions</label><small>Navigation coverage at floor transitions and major landmarks remains mandatory.</small>
    </details>
    <details><summary>Custom beacon profile</summary>{["modelName","mountType","recommendedHeight","defaultBeaconSpacing","coverageRadius","rssiPlanningThreshold","advertisementInterval","txPower","notes"].map(field=><label key={field}>{field}<input value={custom[field]} onChange={e=>setCustom({...custom,[field]:typeof custom[field]==="number"?Number(e.target.value):e.target.value,...(field==="mountType"?{installationType:e.target.value==="Outdoor"?"Pole":e.target.value}:{})})}/></label>)}<button onClick={saveProfile}>Save custom profile</button></details>
    {project.placementNeedsReview&&<p role="alert">{project.floorAnalysis?.scaleAssumed?"Confirm the drawing width before relying on this deployment.":"Geometry changed. Recalculate before relying on this deployment."}</p>}
    {result&&<><h3>Deployment statistics</h3><div className="metrics-grid">{Object.entries(labels).filter(([key])=>result.statistics[key]!==undefined).map(([key,label])=><div key={key}><span>{label}</span><strong>{format(result.statistics[key])}{key==="installationCost"?` ${settings.currency}`:""}</strong></div>)}</div><details open><summary>Engineering warnings ({result.warnings.length})</summary><div className="warning-list">{result.warnings.slice(0,100).map((w,i)=><button className="warning-link" disabled={!Number.isFinite(w.x)} key={i} onClick={()=>{focus(w);if(w.beaconId)setSelection(w.beaconId);}}>{w.message}{Number.isFinite(w.x)?" ↗":""}</button>)}</div><small>Click a located warning to zoom. Up to 100 shown; exports contain all warnings.</small></details></>}
    <details><summary>Export deployment</summary><div className="button-row">{[["json","Deployment JSON"],["csv","Beacon CSV"],["coverage","Coverage report"],["quality","Quality report"],["png","PNG screenshot"]].map(([id,label])=><button key={id} disabled={!result||planner.busy||project.placementNeedsReview} onClick={()=>exportFile(id)}>Export {label}</button>)}</div></details>
    <details><summary>Deployment versions</summary><label>Version name<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="button-row"><button disabled={!result||planner.busy} onClick={()=>save(()=>saveDeployment(project,name,versionId||undefined))}>Save version</button><button disabled={!result||planner.busy} onClick={()=>save(()=>saveDeployment(project,name))}>Save as new version</button></div><label>Version A<select value={versionId} onChange={e=>{setVersionId(e.target.value);const v=versions.find(v=>v.id===e.target.value);if(v)setName(v.name);}}><option value="">Choose version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="button-row"><button disabled={!a||planner.busy} onClick={()=>{save(()=>loadDeployment(project,versionId));setSelection(null);}}>Reload version</button><button disabled={!a} onClick={()=>save(()=>duplicateDeployment(project,versionId))}>Duplicate version</button><button className="danger" disabled={!a} onClick={()=>save(()=>deleteDeployment(project,versionId))}>Delete saved version</button></div><label>Compare with Version B<select value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">Choose version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
      {comparison&&<><p>{a.name} → {b.name}</p>{!comparison.sameGeometry&&<p role="alert">Different geometry/calibration: metrics are not directly comparable.</p>}<table className="version-comparison"><thead><tr><th>Metric</th><th>A</th><th>B</th><th>Δ B−A</th></tr></thead><tbody>{comparison.rows.map(row=><tr key={row.metric}><td>{row.metric}</td><td>{format(row.a)}</td><td>{format(row.b)}</td><td>{format(row.delta)}</td></tr>)}</tbody></table></>}<small>Versions save layout, applied settings and analyzed metrics. Reload then recalculate to refresh coverage.</small>
    </details>
    {comparison&&!comparison.sameAssumptions&&<p role="alert">Versions use different coverage thresholds or sampling resolution; coverage deltas are not directly comparable.</p>}
    {comparison&&!comparison.sameCurrency&&<p role="alert">Versions use different currencies; no cost delta is calculated.</p>}
    {planner.work&&<small>Last analysis: {planner.work.elapsedMs.toFixed(1)} ms · {planner.work.recomputedCells} cells · {planner.work.recomputedEdges} edges · {planner.work.recomputedRegions}/{planner.work.regions} regions.</small>}{(error||localError)&&<p role="alert">{error||localError}</p>}
  </section>;
}
