import React,{useEffect,useRef,useState} from 'react';
import {geometryForProject,deploymentInputSignature} from '../models/deployments.js';
import {downloadFile} from '../models/deploymentExport.js';

const clock=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
export default function SimulationPanel({project,onVisualization}){
  const [start,setStart]=useState(''),[destination,setDestination]=useState(''),[report,setReport]=useState(null),[state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[comparison,setComparison]=useState(null),[a,setA]=useState(''),[b,setB]=useState(''),[speed,setSpeed]=useState(1),[accessible,setAccessible]=useState(false),[avoidStairs,setAvoidStairs]=useState(false),[preferLifts,setPreferLifts]=useState(false);
  const worker=useRef(),sequence=useRef(0),pending=useRef(new Map()),live=useRef(),inputs=useRef(),visualize=useRef(onVisualization);visualize.current=onVisualization;
  const pois=project.objects.filter(o=>o.type==='poi');
  useEffect(()=>{
    const w=new Worker(new URL('../engines/simulationWorker.ts',import.meta.url),{type:'module'});worker.current=w;setReport(null);setState(null);setComparison(null);live.current=null;pending.current.clear();setBusy(false);visualize.current(null);
    w.onmessage=({data})=>{pending.current.delete(data.id);setBusy(pending.current.size>0);if(data.error){setError(data.error);return;}setError('');if(data.report){setReport(data.report);setSpeed(1);}if(data.comparison)setComparison(data.comparison);if(data.state){live.current=data.state;setState(data.state);visualize.current({state:data.state,route:data.report?.route||inputs.current?.route});if(data.report)inputs.current.route=data.report.route;}};
    w.onerror=()=>{setError('Simulation worker failed. Reload to retry.');setBusy(false);live.current=null;};
    return()=>w.terminate();
  },[project.graph,project.objects,project.beaconPlan,project.widthMeters,project.heightMeters,project.drawingWidthPixels,project.planningSettings,start,destination,accessible,avoidStairs,preferLifts]);
  function send(action,data={}){const id=++sequence.current;pending.current.set(id,action);setBusy(true);worker.current.postMessage({id,action,...data});}
  useEffect(()=>{let previous=performance.now();const timer=setInterval(()=>{const now=performance.now();if(live.current?.status==='playing'&&!pending.current.size){send('advance',{value:(now-previous)/1000});previous=now;}else if(live.current?.status!=='playing')previous=now;},100);return()=>clearInterval(timer);},[]);
  function buildInputs(){const geometry=geometryForProject(project),scale=geometry.metersPerPixel;return {graph:project.graph,floorGeometry:geometry,beacons:project.beaconPlan?.beacons||[],pois:pois.map(p=>({...p,floorId:p.floorId||project.graph.nodes[0]?.floorId||'floor-1',worldX:p.x*scale,worldY:p.y*scale})),configuration:{walkingSpeedMps:1.35,sampleStep:.25,accessibleOnly:accessible,avoidStairs,preferLifts}};}
  function prepare(){try{inputs.current=buildInputs();send('prepare',{inputs:inputs.current,start,destination});}catch(e){setError(e.message);}}
  function compare(){try{const first=project.deployments.find(v=>v.id===a),second=project.deployments.find(v=>v.id===b);if(!first||!second)throw new Error('Choose two saved versions.');const signature=deploymentInputSignature(project);if(first.inputSignature!==signature||second.inputSignature!==signature)throw new Error('Both versions must match the current geometry and graph before comparing routes.');send('compare',{inputs:buildInputs(),start,destination,a:{name:first.name,beacons:first.plan.beacons},b:{name:second.name,beacons:second.plan.beacons}});}catch(e){setError(e.message);}}
  const stats=report?.statistics;
  return <section className="panel-section simulation-panel"><h2>Navigation simulation</h2><small>Geometry-based planning only. No Bluetooth, live positioning or RF prediction. Signal is a 0–100 proximity score, not dBm.</small>
    <label>Start POI<select value={start} onChange={e=>setStart(e.target.value)}><option value="">Choose start</option>{pois.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
    <label>Destination POI<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose destination</option>{pois.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
    {[[accessible,setAccessible,'Accessible route'],[avoidStairs,setAvoidStairs,'Avoid stairs in simulation'],[preferLifts,setPreferLifts,'Prefer lifts in simulation']].map(([value,set,label])=><label key={label} className="check-label"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{label}</label>)}
    <button disabled={busy||!start||!destination||project.placementNeedsReview} onClick={prepare}>Prepare simulation</button>
    {report&&<><div className="button-row">{['play','pause','resume','stop','replay'].map(action=><button key={action} disabled={busy} onClick={()=>send(action)}>{action[0].toUpperCase()+action.slice(1)}</button>)}</div>
      <label>Playback speed<select value={speed} onChange={e=>{setSpeed(Number(e.target.value));send('speed',{value:Number(e.target.value)});}}>{[1,2,5,10].map(n=><option value={n} key={n}>{n}x</option>)}</select></label>
      <label>Simulation timeline<input type="range" min="0" max={stats.walkingTime||0} step=".1" value={state?.elapsed||0} onChange={e=>send('seek',{value:Number(e.target.value)})}/></label><small>{clock(state?.elapsed||0)} / {clock(stats.walkingTime)} · {state?.status}</small>
      <h3>Virtual walker</h3><p>Position: ({state?.worldX.toFixed(2)}, {state?.worldY.toFixed(2)}) m<br/>Floor: {state?.floorId}{state?.transition?' · transition unverified':''}<br/>Graph node: {state?.nodeId} · Corridor: {state?.edgeId||'None'}<br/>Nearest beacon: {state?.nearestBeacon||'None'} · {state?.nearestDistance==null?'Unavailable':`${state.nearestDistance.toFixed(2)} m`}<br/>Previous beacon: {state?.previousBeacon||'None'}<br/>Current beacon: {state?.activeBeacon||'None'} · {state?.activeDistance==null?'Unavailable':`${state.activeDistance.toFixed(2)} m`} · Upcoming: {state?.upcomingBeacon||'None'}<br/>Coverage: {state?.coverageState} · Signal score: {state?.signal==null?'Unavailable':state.signal.toFixed(1)}<br/>Handovers: {state?.handovers||0} · Last transition: {state?.transitionTime==null?'None':clock(state.transitionTime)}</p>
      <h3>Navigation quality report</h3><div className="metrics-grid">{[['Distance (m)',stats.distance],['Walking time (s)',stats.walkingTime],['Handovers',stats.handovers],['Mean handover interval (m)',stats.averageDistanceBetweenHandovers],['Coverage %',stats.coveragePercentage],['Reliability score',stats.reliabilityScore],['Navigation score',stats.navigationScore],['Longest gap (m)',stats.longestGap],['Maximum beacon separation (m)',stats.maximumDistanceBetweenActiveBeacons],['Weak sections',stats.weakCoverageSections.length],['Dead zones',stats.deadZones.length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{Number(value).toFixed(2)}</strong></div>)}</div><p>Continuous coverage: {stats.continuousCoverage?'Yes':'No'}<br/>Off-graph approach: {stats.approachDistance.toFixed(2)} m · {stats.approachVerified?'Verified attachment':'Unverified, excluded from graph metrics'}<br/>Floors: {stats.floorsTraversed.join(' → ')}<br/>Ordered nodes: {stats.orderedNodes.join(' → ')}</p>
      {report.warnings.map((w,i)=><p className="warning-text" key={i}>{w}</p>)}<small>Route validation samples at {report.sampleStep} m, with exact geometry clipping. Scores are planning heuristics, not installation certification.</small>
      <details><summary>Event timeline ({report.events.length})</summary><ol className="simulation-events">{report.events.slice(0,250).map((e,i)=><li key={i} className={e.time<=(state?.elapsed||0)?'visited-event':''}>{clock(e.time)} {e.message}</li>)}</ol><small>Up to 250 events shown; exports include all.</small></details>
      <div className="button-row"><button onClick={()=>downloadFile('navigation-report.json',report)}>Export navigation report</button><button onClick={()=>downloadFile('navigation-log.json',report.events)}>Export navigation log</button></div>
    </>}
    <details><summary>Compare route deployments</summary>{[[a,setA,'Simulation Deployment A'],[b,setB,'Simulation Deployment B']].map(([value,set,label])=><label key={label}>{label}<select value={value} onChange={e=>set(e.target.value)}><option value="">Choose version</option>{(project.deployments||[]).map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label>)}<button disabled={busy||!start||!destination||!a||!b} onClick={compare}>Compare navigation</button>
      {comparison&&<><p>{comparison.recommendation}</p>{comparison.warnings.map((w,i)=><p className="warning-text" key={i}>{w}</p>)}<table className="version-comparison"><thead><tr><th>Metric</th><th>{comparison.a.name}</th><th>{comparison.b.name}</th></tr></thead><tbody>{['beaconCount','coveragePercentage','navigationScore','walkingQuality','handovers','longestGap'].map(key=><tr key={key}><td>{key}</td><td>{comparison.a[key].toFixed(2)}</td><td>{comparison.b[key].toFixed(2)}</td></tr>)}</tbody></table><button onClick={()=>downloadFile('navigation-comparison.json',comparison)}>Export navigation comparison</button></>}
    </details>{busy&&<small>Updating simulation…</small>}{error&&<p role="alert">{error}</p>}
  </section>;
}
